// Code generated by hertz generator.

package order_web

import (
	"context"
	"strconv"

	"github.com/pkg/errors"

	"StayEaseGo/apis/order_web/biz/global"
	order_web "StayEaseGo/apis/order_web/biz/model/order_web"
	"StayEaseGo/pkg/result"
	"StayEaseGo/pkg/xerr"
	pb "StayEaseGo/srvs/order_srv/proto/gen"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/jinzhu/copier"
)

// CreateHomestayOrder .
// @router /api/v1/order [POST]
func CreateHomestayOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order_web.CreateHomestayOrderReq
	err = c.BindAndValidate(&req)
	if err != nil {
		result.HttpResult(c, consts.StatusBadRequest, nil, xerr.NewErrCodeMsg(xerr.REUQEST_PARAM_ERROR, err.Error()))
		return
	}
	userID, err := getUserID(c)
	if err != nil {
		result.HttpResult(c, consts.StatusUnauthorized, nil, err)
		return
	}

	var rpcReq pb.CreateHomestayOrderReq
	copier.Copy(&rpcReq, &req)
	rpcReq.UserId = userID
	rpcResp, err := global.OrderSrvClient.CreateHomestayOrder(ctx, &rpcReq)
	if err != nil {
		result.HttpResult(c, consts.StatusInternalServerError, nil, errors.Wrap(err, "create homestay order failed"))
	}
	resp := &order_web.CreateHomestayOrderResp{
		Sn: rpcResp.Sn,
	}
	result.HttpResult(c, consts.StatusOK, resp, nil)
}

// HomestayOrderDetail .
// @router /api/v1/order/detail [POST]
func HomestayOrderDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order_web.HomestayOrderDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		result.HttpResult(c, consts.StatusUnauthorized, nil, err)
		return
	}
	userID, err := getUserID(c)
	if err != nil {
		result.HttpResult(c, consts.StatusUnauthorized, nil, err)
		return
	}
	rpcResp, err := global.OrderSrvClient.HomestayOrderDetail(ctx, &pb.HomestayOrderDetailReq{})
	if err != nil {
		result.HttpResult(c, consts.StatusInternalServerError, nil, errors.Wrap(err, "get homestay detail failed"))
		return
	}

	if rpcResp == nil || rpcResp.HomestayOrder.UserId != userID {
		result.HttpResult(c, consts.StatusInternalServerError, nil, xerr.NewErrCodeMsg(xerr.DB_ERROR, "can not find order or order not belong to you"))
		return
	}
	resp := new(order_web.HomestayOrder)
	copier.Copy(&resp, &rpcResp.HomestayOrder)
	result.HttpResult(c, consts.StatusOK, resp, nil)
}

// UserHomestayOrderList .
// @router /api/v1/order/list [POST]
func UserHomestayOrderList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order_web.UserHomestayOrderListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		result.HttpResult(c, consts.StatusBadRequest, nil, xerr.NewErrCodeMsg(xerr.REUQEST_PARAM_ERROR, err.Error()))
		return
	}
	userID, err := getUserID(c)
	if err != nil {
		result.HttpResult(c, consts.StatusUnauthorized, nil, err)
		return
	}
	rpcResp, err := global.OrderSrvClient.UserHomestayOrderList(ctx, &pb.UserHomestayOrderListReq{
		LastId:      req.LastId,
		PageSize:    req.PageSize,
		TraderState: req.TraderState,
		UserId:      userID,
	})
	if err != nil {
		result.HttpResult(c, consts.StatusInternalServerError, nil, errors.Wrap(err, "get order list failed"))
		return
	}
	resp := make([]*order_web.HomestayOrder, len(rpcResp.List))
	for i := range len(rpcResp.List) {
		copier.Copy(&resp[i], &rpcResp.List[i])
	}

	result.HttpResult(c, consts.StatusOK, resp, nil)
}

func getUserID(c *app.RequestContext) (int64, error) {
	v, exist := c.Get("userID")
	if !exist || v == nil {
		return 0, xerr.NewErrCode(xerr.TOKEN_PARSE_ERROR)
	}
	i, err := strconv.ParseInt(v.(string), 10, 64)
	if err != nil {
		return 0, xerr.NewErrCode(xerr.TOKEN_PARSE_ERROR)
	}
	return i, nil
}
