// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	user_web "StayEaseGo/apis/user_web/biz/router/user_web"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	user_web.Register(r)
}
