// Code generated by hertz generator.

package homestay_web

import (
	"StayEaseGo/apis/homestay_web/biz/handler/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createhomestayMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _homestayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homestaydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homestaylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homestaybusinessbossdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homestay0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
