// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	order_web "StayEaseGo/apis/order_web/biz/router/order_web"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order_web.Register(r)

}
