// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	payment_web "StayEaseGo/apis/payment_web/biz/router/payment_web"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	payment_web.Register(r)
}
