// Code generated by hertz generator.

package payment_web

import (
	"StayEaseGo/apis/payment_web/biz/handler/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _payMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wxpayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _thirdpaymentwxpayMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}
}

func _thirdpaymentwxpaycallbackMw() []app.HandlerFunc {
	// your code...
	return nil
}
