// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: payment_web.proto

package payment_web

import (
	_ "StayEaseGo/apis/payment_web/biz/model/api"
	_ "StayEaseGo/apis/payment_web/biz/model/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThirdPaymentWxPayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn     string `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty" form:"orderSn" query:"orderSn"`
	ServiceType string `protobuf:"bytes,2,opt,name=serviceType,proto3" json:"serviceType,omitempty" form:"serviceType" query:"serviceType"`
}

func (x *ThirdPaymentWxPayReq) Reset() {
	*x = ThirdPaymentWxPayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_web_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPaymentWxPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPaymentWxPayReq) ProtoMessage() {}

func (x *ThirdPaymentWxPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_web_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPaymentWxPayReq.ProtoReflect.Descriptor instead.
func (*ThirdPaymentWxPayReq) Descriptor() ([]byte, []int) {
	return file_payment_web_proto_rawDescGZIP(), []int{0}
}

func (x *ThirdPaymentWxPayReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *ThirdPaymentWxPayReq) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

type ThirdPaymentWxPayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Appid     string `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty" form:"appid" query:"appid"`
	NonceStr  string `protobuf:"bytes,2,opt,name=nonceStr,proto3" json:"nonceStr,omitempty" form:"nonceStr" query:"nonceStr"`
	PaySign   string `protobuf:"bytes,3,opt,name=paySign,proto3" json:"paySign,omitempty" form:"paySign" query:"paySign"`
	Package   string `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty" form:"package" query:"package"`
	Timestamp string `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty" form:"timestamp" query:"timestamp"`
	SignType  string `protobuf:"bytes,6,opt,name=signType,proto3" json:"signType,omitempty" form:"signType" query:"signType"`
}

func (x *ThirdPaymentWxPayResp) Reset() {
	*x = ThirdPaymentWxPayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_web_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPaymentWxPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPaymentWxPayResp) ProtoMessage() {}

func (x *ThirdPaymentWxPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_web_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPaymentWxPayResp.ProtoReflect.Descriptor instead.
func (*ThirdPaymentWxPayResp) Descriptor() ([]byte, []int) {
	return file_payment_web_proto_rawDescGZIP(), []int{1}
}

func (x *ThirdPaymentWxPayResp) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *ThirdPaymentWxPayResp) GetNonceStr() string {
	if x != nil {
		return x.NonceStr
	}
	return ""
}

func (x *ThirdPaymentWxPayResp) GetPaySign() string {
	if x != nil {
		return x.PaySign
	}
	return ""
}

func (x *ThirdPaymentWxPayResp) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ThirdPaymentWxPayResp) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ThirdPaymentWxPayResp) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

type ThirdPaymentWxPayCallbackReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ThirdPaymentWxPayCallbackReq) Reset() {
	*x = ThirdPaymentWxPayCallbackReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_web_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPaymentWxPayCallbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPaymentWxPayCallbackReq) ProtoMessage() {}

func (x *ThirdPaymentWxPayCallbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_web_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPaymentWxPayCallbackReq.ProtoReflect.Descriptor instead.
func (*ThirdPaymentWxPayCallbackReq) Descriptor() ([]byte, []int) {
	return file_payment_web_proto_rawDescGZIP(), []int{2}
}

type ThirdPaymentWxPayCallbackResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnCode string `protobuf:"bytes,1,opt,name=returnCode,proto3" json:"returnCode,omitempty" form:"returnCode" query:"returnCode"`
}

func (x *ThirdPaymentWxPayCallbackResp) Reset() {
	*x = ThirdPaymentWxPayCallbackResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_web_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdPaymentWxPayCallbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdPaymentWxPayCallbackResp) ProtoMessage() {}

func (x *ThirdPaymentWxPayCallbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_web_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdPaymentWxPayCallbackResp.ProtoReflect.Descriptor instead.
func (*ThirdPaymentWxPayCallbackResp) Descriptor() ([]byte, []int) {
	return file_payment_web_proto_rawDescGZIP(), []int{3}
}

func (x *ThirdPaymentWxPayCallbackResp) GetReturnCode() string {
	if x != nil {
		return x.ReturnCode
	}
	return ""
}

var File_payment_web_proto protoreflect.FileDescriptor

var file_payment_web_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62,
	0x1a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a, 0x14, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x15,
	0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50, 0x61,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x53, 0x74, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x53, 0x69, 0x67,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x69, 0x67,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x22, 0x3f, 0x0a, 0x1d, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x32, 0xf0, 0x01, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x71, 0x0a, 0x11, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x12, 0x21, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x77, 0x65, 0x62, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x15,
	0xd2, 0xc1, 0x18, 0x11, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x79, 0x2f,
	0x77, 0x78, 0x70, 0x61, 0x79, 0x12, 0x72, 0x0a, 0x19, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x12, 0x29, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62,
	0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50,
	0x61, 0x79, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x2a, 0x2e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62, 0x2e, 0x54, 0x68, 0x69, 0x72,
	0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x57, 0x78, 0x50, 0x61, 0x79, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x33, 0x5a, 0x31, 0x53, 0x74, 0x61,
	0x79, 0x45, 0x61, 0x73, 0x65, 0x47, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62, 0x2f, 0x62, 0x69, 0x7a, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x65, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_payment_web_proto_rawDescOnce sync.Once
	file_payment_web_proto_rawDescData = file_payment_web_proto_rawDesc
)

func file_payment_web_proto_rawDescGZIP() []byte {
	file_payment_web_proto_rawDescOnce.Do(func() {
		file_payment_web_proto_rawDescData = protoimpl.X.CompressGZIP(file_payment_web_proto_rawDescData)
	})
	return file_payment_web_proto_rawDescData
}

var file_payment_web_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payment_web_proto_goTypes = []interface{}{
	(*ThirdPaymentWxPayReq)(nil),          // 0: payment_web.ThirdPaymentWxPayReq
	(*ThirdPaymentWxPayResp)(nil),         // 1: payment_web.ThirdPaymentWxPayResp
	(*ThirdPaymentWxPayCallbackReq)(nil),  // 2: payment_web.ThirdPaymentWxPayCallbackReq
	(*ThirdPaymentWxPayCallbackResp)(nil), // 3: payment_web.ThirdPaymentWxPayCallbackResp
}
var file_payment_web_proto_depIdxs = []int32{
	0, // 0: payment_web.payment.ThirdPaymentWxPay:input_type -> payment_web.ThirdPaymentWxPayReq
	2, // 1: payment_web.payment.ThirdPaymentWxPayCallback:input_type -> payment_web.ThirdPaymentWxPayCallbackReq
	1, // 2: payment_web.payment.ThirdPaymentWxPay:output_type -> payment_web.ThirdPaymentWxPayResp
	3, // 3: payment_web.payment.ThirdPaymentWxPayCallback:output_type -> payment_web.ThirdPaymentWxPayCallbackResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_web_proto_init() }
func file_payment_web_proto_init() {
	if File_payment_web_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_payment_web_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPaymentWxPayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_web_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPaymentWxPayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_web_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPaymentWxPayCallbackReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_web_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdPaymentWxPayCallbackResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payment_web_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_web_proto_goTypes,
		DependencyIndexes: file_payment_web_proto_depIdxs,
		MessageInfos:      file_payment_web_proto_msgTypes,
	}.Build()
	File_payment_web_proto = out.File
	file_payment_web_proto_rawDesc = nil
	file_payment_web_proto_goTypes = nil
	file_payment_web_proto_depIdxs = nil
}
