// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	homestay_web "StayEaseGo/apis/homestay_web/biz/router/homestay_web"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	homestay_web.Register(r)

}
