// Code generated by hertz generator.

package order_web

import (
	"StayEaseGo/apis/order_web/biz/handler/middleware"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.JWTAuth()}

}

func _createhomestayorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _homestayorderdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userhomestayorderlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
